 addpath(['/home1/brainard/dpl/trunk/RenderToolbox_2.0/DataHandling', ...
     '/home1/brainard/dpl/trunk/RenderToolbox_2.0/ImageProcessing', ...
     '/home1/brainard/dpl/trunk/RenderToolbox_2.0/PBRTRendering', ...
     '/home1/brainard/dpl/trunk/RenderToolbox_2.0/ParameterProcessing', ...
     '/home1/brainard/dpl/trunk/RenderToolbox_2.0/RadianceRendering', ...
     '/home1/brainard/dpl/trunk/RenderToolbox_2.0/RenderDataFiles', ...
     '/home1/brainard/dpl/trunk/RenderToolbox_2.0/RenderToolboxPathHandling', ...
     '/home1/brainard/dpl/trunk/RenderToolbox_2.0/ToplevelFunctions']);

%call batchrender script
Render_BatchRender_cluster;
