function Render_RenderPBRT(currentConditions,objectMaterialParams,lightMaterialParams)
% 8 junly 2006 dpl wrote it.

% assume we're in the experiment directory
% assume pbrt file is in this directory and called [sceneName].pbrt

%get stuff from conditions, some for use in bei's code below
temporaryDirectory=currentConditions.temporaryDirectory;
imageDirectory=currentConditions.imageDirectory;
wavelengths=currentConditions.wls;
sceneName=currentConditions.sceneName;
currentConditionNumber=currentConditions.currentConditionNumber;
resolution=currentConditions.imageRes;

%get spectrum for each object
numWavelengths=length(wavelengths);
numObjects=length(objectMaterialParams);
objectNames={objectMaterialParams.name};
objectSpectrum={objectMaterialParams.spectrum};

%read original pbrt script generated by mayapbrt
pbrtScript=Render_ReadInPBRTScript(currentConditions);

%create a new pbrt script for each wavelength of this condition
fileNames=Render_GeneratePBRTScripts(currentConditions,objectMaterialParams,lightMaterialParams,pbrtScript);

%render these new pbrt scripts
Render_RenderPBRTScripts(currentConditions,fileNames);

%generate picture matrix from raw pbrt output
Render_RawPBRTToPicMatrix(currentConditions,fileNames);




%%now try to run through rest of code!
%%***should put all this into a separate function that runs for both the
%%radiance and the pbrt renderers.


%make S image and cone images
display('generate and write image data...');
Render_MakeSimg(currentConditions);

%convert into cone image
Render_MakeConeImage(currentConditions);

%convert into monitor image
display('generating and writing monitor image...');
Render_MakeMonitorImage(currentConditions);
